// SvelteFoodFacts/src/lib/components/display/AbsoluteDate.svelte
<script lang="ts">
  let { value }: { value: string } = $props();

  let formattedDate = $derived.by(() => {
    if (!value) {
      return '';
    }
    const date = new Date(value);
    return date.toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
    });
  });
</script>

<span class="absolute-date">{formattedDate}</span>

<style>
  .absolute-date {
    color: #333;
  }
</style>

// SolidFoodFacts/src/components/display/AbsoluteDate.tsx
import { createMemo } from 'solid-js';
import './AbsoluteDate.css';

interface AbsoluteDateProps {
  value: string;
}

export default function AbsoluteDate(props: AbsoluteDateProps) {
  const formattedDate = createMemo(() => {
    if (!props.value) {
      return '';
    }
    const date = new Date(props.value);
    return date.toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
    });
  });

  return <span class="absolute-date">{formattedDate()}</span>;
}
