// ReactFoodFacts/src/components/display/ProductImage.tsx
import { memo, useState, useCallback } from 'react';
import './ProductImage.css';

interface ProductImageProps {
  value: string;
  size?: 'small' | 'large';
}

export const ProductImage = memo(({ value, size = 'small' }: ProductImageProps) => {
  const [imageLoaded, setImageLoaded] = useState(false);
  const [imageError, setImageError] = useState(false);

  const onImageLoad = useCallback(() => {
    setImageLoaded(true);
  }, []);

  const onImageError = useCallback(() => {
    setImageError(true);
  }, []);

  return (
    <div className={`product-image ${size}`}>
      {!imageError ? (
        <img
          src={value}
          alt="Product image"
          onLoad={onImageLoad}
          onError={onImageError}
          className={imageLoaded ? 'loaded' : ''}
        />
      ) : (
        <div className="image-placeholder">No image</div>
      )}
    </div>
  );
});

ProductImage.displayName = 'ProductImage';

// SolidFoodFacts/src/components/display/ProductImage.tsx
import { createSignal, Show } from 'solid-js';
import './ProductImage.css';

interface ProductImageProps {
  value: string;
  size?: 'small' | 'large';
}

export default function ProductImage(props: ProductImageProps) {
  const [imageLoaded, setImageLoaded] = createSignal(false);
  const [imageError, setImageError] = createSignal(false);

  const size = () => props.size || 'small';

  return (
    <div class={`product-image ${size()}`}>
      <Show
        when={!imageError()}
        fallback={<div class="image-placeholder">No image</div>}
      >
        <img
          src={props.value}
          alt="Product image"
          class={imageLoaded() ? 'loaded' : ''}
          onLoad={() => setImageLoaded(true)}
          onError={() => setImageError(true)}
        />
      </Show>
    </div>
  );
}
