// ReactFoodFacts/src/components/display/TruncatedText.tsx
import { memo, useState, useCallback } from 'react';
import './TruncatedText.css';

interface TruncatedTextProps {
  value: string | null | undefined;
  maxLength?: number;
}

export const TruncatedText = memo(({ value, maxLength = 50 }: TruncatedTextProps) => {
  const [isExpanded, setIsExpanded] = useState(false);

  const toggleExpanded = useCallback(() => {
    setIsExpanded((prev) => !prev);
  }, []);

  const shouldTruncate = value ? value.length > maxLength : false;

  let displayValue: string;
  if (!value) {
    displayValue = '';
  } else if (shouldTruncate && !isExpanded) {
    displayValue = value.substring(0, maxLength - 3) + '...';
  } else {
    displayValue = value;
  }

  return (
    <div className="truncated-text">
      <span className="text-content">{displayValue}</span>
      {shouldTruncate && (
        <button onClick={toggleExpanded} className="toggle-button" type="button">
          {isExpanded ? 'Show less' : 'Show more'}
        </button>
      )}
    </div>
  );
});

TruncatedText.displayName = 'TruncatedText';

// SolidFoodFacts/src/components/display/TruncatedText.tsx
import { createSignal, createMemo, Show } from 'solid-js';
import './TruncatedText.css';

interface TruncatedTextProps {
  value: string;
  maxLength?: number;
}

export default function TruncatedText(props: TruncatedTextProps) {
  const [isExpanded, setIsExpanded] = createSignal(false);
  const maxLength = () => props.maxLength ?? 50;

  const shouldTruncate = createMemo(() => (props.value?.length ?? 0) > maxLength());

  const displayText = createMemo(() => {
    const text = props.value || '';
    if (shouldTruncate() && !isExpanded()) {
      return text.substring(0, maxLength() - 3) + '...';
    }
    return text;
  });

  return (
    <div class="truncated-text">
      <span class="text-content">{displayText()}</span>
      <Show when={shouldTruncate()}>
        <button
          class="toggle-button"
          onClick={() => setIsExpanded(!isExpanded())}
          type="button"
        >
          {isExpanded() ? 'Show less' : 'Show more'}
        </button>
      </Show>
    </div>
  );
}
