// SolidFoodFacts/src/components/display/AbsoluteDate.tsx
import { createMemo } from 'solid-js';
import './AbsoluteDate.css';

interface AbsoluteDateProps {
  value: string;
}

export default function AbsoluteDate(props: AbsoluteDateProps) {
  const formattedDate = createMemo(() => {
    if (!props.value) {
      return '';
    }
    const date = new Date(props.value);
    return date.toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
    });
  });

  return <span class="absolute-date">{formattedDate()}</span>;
}

// ReactFoodFacts/src/components/display/AbsoluteDate.tsx
import { memo, useMemo } from 'react';

interface AbsoluteDateProps {
  value: string | null | undefined;
}

export const AbsoluteDate = memo(({ value }: AbsoluteDateProps) => {
  const formattedDate = useMemo(() => {
    let result: string;
    if (!value) {
      result = '';
    } else {
      const date = new Date(value);
      result = date.toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'short',
        day: 'numeric',
      });
    }
    return result;
  }, [value]);

  return <span className="absolute-date">{formattedDate}</span>;
});

AbsoluteDate.displayName = 'AbsoluteDate';
