// SolidFoodFacts/src/components/display/BooleanYesNo.tsx
import { Show } from 'solid-js';
import './BooleanYesNo.css';

interface BooleanYesNoProps {
  value: boolean | null | undefined;
}

export default function BooleanYesNo(props: BooleanYesNoProps) {
  return (
    <Show when={props.value} fallback={<span class="boolean-yesno no">No</span>}>
      <span class="boolean-yesno yes">Yes</span>
    </Show>
  );
}

// ReactFoodFacts/src/components/display/BooleanYesNo.tsx
import { memo } from 'react';
import './BooleanYesNo.css';

interface BooleanYesNoProps {
  value: boolean;
}

export const BooleanYesNo = memo(({ value }: BooleanYesNoProps) => {
  const displayText = value ? 'Yes' : 'No';
  const cssClass = value ? 'yes' : 'no';

  return <span className={`boolean-yesno ${cssClass}`}>{displayText}</span>;
});

BooleanYesNo.displayName = 'BooleanYesNo';
