// SolidFoodFacts/src/components/display/GradeBadge.tsx
import { createMemo } from 'solid-js';
import './GradeBadge.css';

interface GradeBadgeProps {
  value: string | null | undefined;
}

export default function GradeBadge(props: GradeBadgeProps) {
  const gradeClass = createMemo(() => {
    switch (props.value?.toUpperCase()) {
      case 'A':
        return 'grade-a';
      case 'B':
        return 'grade-b';
      case 'C':
        return 'grade-c';
      case 'D':
        return 'grade-d';
      case 'F':
        return 'grade-f';
      default:
        return 'grade-unknown';
    }
  });

  return <span class={`grade-badge ${gradeClass()}`}>{props.value}</span>;
}

// ReactFoodFacts/src/components/display/GradeBadge.tsx
import { memo, useMemo } from 'react';
import './GradeBadge.css';

interface GradeBadgeProps {
  grade: string | null | undefined;
}

export const GradeBadge = memo(({ grade }: GradeBadgeProps) => {
  const gradeClass = useMemo(() => {
    const gradeUpper = grade?.toUpperCase();
    let result: string;
    if (gradeUpper === 'A') {
      result = 'grade-a';
    } else if (gradeUpper === 'B') {
      result = 'grade-b';
    } else if (gradeUpper === 'C') {
      result = 'grade-c';
    } else if (gradeUpper === 'D') {
      result = 'grade-d';
    } else if (gradeUpper === 'F') {
      result = 'grade-f';
    } else {
      result = 'grade-unknown';
    }
    return result;
  }, [grade]);

  return (
    <span className={`grade-badge ${gradeClass}`}>
      {` ${grade} `}
    </span>
  );
});

GradeBadge.displayName = 'GradeBadge';
