// SolidFoodFacts/src/components/display/LargeCounter.tsx
import { createMemo } from 'solid-js';
import './LargeCounter.css';

interface LargeCounterProps {
  value: number | undefined;
}

export default function LargeCounter(props: LargeCounterProps) {
  const formattedValue = createMemo(() => {
    const value = props.value;
    if (value === undefined || value === null) {
      return '0';
    }
    if (value >= 1_000_000) {
      return (value / 1_000_000).toFixed(1) + 'M';
    }
    if (value >= 1_000) {
      return value.toLocaleString('en-US');
    }
    return value.toString();
  });

  return <span class="large-counter">{formattedValue()}</span>;
}

// ReactFoodFacts/src/components/display/LargeCounter.tsx
import { memo, useMemo } from 'react';
import './LargeCounter.css';

interface LargeCounterProps {
  value: number | null | undefined;
}

export const LargeCounter = memo(({ value }: LargeCounterProps) => {
  const formattedValue = useMemo(() => {
    let result: string;
    if (value === null || value === undefined) {
      result = '0';
    } else if (value >= 1000000) {
      result = (value / 1000000).toFixed(1) + 'M';
    } else if (value >= 1000) {
      result = value.toLocaleString('en-US');
    } else {
      result = value.toString();
    }
    return result;
  }, [value]);

  return <span className="large-counter">{formattedValue}</span>;
});

LargeCounter.displayName = 'LargeCounter';
