// SolidFoodFacts/src/components/display/NovaDots.tsx
import { createMemo, For } from 'solid-js';
import './NovaDots.css';

interface NovaDotsProps {
  value: number;
}

export default function NovaDots(props: NovaDotsProps) {
  const rating = createMemo(() => {
    if (props.value < 1) return 1;
    if (props.value > 4) return 4;
    return Math.floor(props.value);
  });

  const dots = createMemo(() => {
    const filledCount = rating();
    const result = [];
    for (let i = 1; i <= 4; i++) {
      result.push({ filled: i <= filledCount });
    }
    return result;
  });

  return (
    <div class="nova-dots">
      <For each={dots()}>
        {(dot) => <span class={`dot ${dot.filled ? 'filled' : ''}`}></span>}
      </For>
    </div>
  );
}

// ReactFoodFacts/src/components/display/NovaDots.tsx
import { memo, useMemo } from 'react';
import './NovaDots.css';

interface NovaDotsProps {
  rating: number | null | undefined;
}

export const NovaDots = memo(({ rating }: NovaDotsProps) => {
  const dots = useMemo(() => {
    let filledCount: number;
    if (!rating || rating < 1) {
      filledCount = 1;
    } else if (rating > 4) {
      filledCount = 4;
    } else {
      filledCount = Math.floor(rating);
    }

    const result = [];
    for (let i = 1; i <= 4; i++) {
      result.push(
        <span key={i} className={`dot${i <= filledCount ? ' filled' : ''}`} />
      );
    }
    return result;
  }, [rating]);

  return <div className="nova-dots">{dots}</div>;
});

NovaDots.displayName = 'NovaDots';
