// SolidFoodFacts/src/components/display/ProgressBar.tsx
import { createMemo } from 'solid-js';
import './ProgressBar.css';

interface ProgressBarProps {
  value: number;
}

export default function ProgressBar(props: ProgressBarProps) {
  const percentage = createMemo(() => {
    if (props.value < 0) return 0;
    if (props.value > 100) return 100;
    return props.value;
  });

  const colorClass = createMemo(() => {
    const pct = percentage();
    if (pct >= 70) return 'high';
    if (pct >= 40) return 'medium';
    return 'low';
  });

  return (
    <div class="progress-bar-container">
      <div class={`progress-bar ${colorClass()}`}>
        <div class="progress-fill" style={{ width: `${percentage()}%` }}></div>
      </div>
      <span class="progress-text">{percentage()}%</span>
    </div>
  );
}

// ReactFoodFacts/src/components/display/ProgressBar.tsx
import { useMemo } from 'react';
import './ProgressBar.css';

interface ProgressBarProps {
  value: number;
}

export const ProgressBar = ({ value }: ProgressBarProps) => {
  const percentage = useMemo(() => {
    let result: number;
    if (value < 0) {
      result = 0;
    } else if (value > 100) {
      result = 100;
    } else {
      result = value;
    }
    return result;
  }, [value]);

  const colorClass = useMemo(() => {
    let result: string;
    if (percentage >= 70) {
      result = 'high';
    } else if (percentage >= 40) {
      result = 'medium';
    } else {
      result = 'low';
    }
    return result;
  }, [percentage]);

  return (
    <div className="progress-bar-container">
      <div className={`progress-bar ${colorClass}`}>
        <div className="progress-fill" style={{ width: `${percentage}%` }}></div>
      </div>
      <span className="progress-text">{percentage}%</span>
    </div>
  );
};
