// SolidFoodFacts/src/components/display/StarRating.tsx
import { createMemo, For } from 'solid-js';
import './StarRating.css';

interface StarRatingProps {
  value: number;
  maxStars?: number;
}

export default function StarRating(props: StarRatingProps) {
  const maxStars = () => props.maxStars ?? 5;

  const stars = createMemo(() => {
    const rating = Number(props.value) || 0;
    const fullStars = Math.floor(rating);
    const hasHalfStar = rating % 1 >= 0.5;
    const emptyStars = maxStars() - fullStars - (hasHalfStar ? 1 : 0);

    return {
      full: Array(fullStars).fill(0),
      half: hasHalfStar ? [0] : [],
      empty: Array(Math.max(0, emptyStars)).fill(0),
    };
  });

  return (
    <div class="star-rating">
      <For each={stars().full}>
        {() => <span class="star full">★</span>}
      </For>
      <For each={stars().half}>
        {() => <span class="star half">★</span>}
      </For>
      <For each={stars().empty}>
        {() => <span class="star empty">☆</span>}
      </For>
      <span class="rating-value">{props.value}</span>
    </div>
  );
}

// ReactFoodFacts/src/components/display/StarRating.tsx
import { memo, useMemo } from 'react';
import './StarRating.css';

interface StarRatingProps {
  value: number | null | undefined;
  maxStars?: number;
}

export const StarRating = memo(({ value, maxStars = 5 }: StarRatingProps) => {
  const stars = useMemo(() => {
    const rating = value ?? 0;
    const fullStars = Math.floor(rating);
    const hasHalfStar = rating % 1 >= 0.5;
    const emptyStars = maxStars - fullStars - (hasHalfStar ? 1 : 0);

    return {
      full: Array(fullStars).fill(0),
      half: hasHalfStar ? [0] : [],
      empty: Array(emptyStars).fill(0),
    };
  }, [value, maxStars]);

  return (
    <div className="star-rating">
      {stars.full.map((_, i) => (
        <span key={`full-${i}`} className="star full">★</span>
      ))}
      {stars.half.map((_, i) => (
        <span key={`half-${i}`} className="star half">★</span>
      ))}
      {stars.empty.map((_, i) => (
        <span key={`empty-${i}`} className="star empty">☆</span>
      ))}
      <span className="rating-value">{value}</span>
    </div>
  );
});

StarRating.displayName = 'StarRating';
