// SvelteFoodFacts/src/lib/components/table/CellRenderer.svelte
<script lang="ts">
  import type { ColumnDataType } from 'shared-types';
  import {
    AbsoluteDate,
    ProductLink,
    ProgressBar,
    GradeBadge,
    NovaDots,
    BooleanYesNo,
    LargeCounter,
    ProductImage,
    DecimalUnits,
    ColorPill,
    RelativeDate,
    TimeFormat,
    TruncatedText,
    StarRating,
  } from '$lib/components/display';

  let {
    value,
    dataType,
    column,
    row,
    unit,
  }: {
    value: any;
    dataType: ColumnDataType;
    column: string;
    row: Record<string, any>;
    unit?: string;
  } = $props();
</script>

{#if dataType === 'product-link'}
  <ProductLink {value} />
{:else if dataType === 'progress-bar'}
  <ProgressBar {value} />
{:else if dataType === 'grade-badge'}
  <GradeBadge {value} />
{:else if dataType === 'nova-dots'}
  <NovaDots {value} />
{:else if dataType === 'boolean-yesno'}
  <BooleanYesNo {value} />
{:else if dataType === 'large-counter'}
  <LargeCounter {value} />
{:else if dataType === 'product-image'}
  <ProductImage {value} />
{:else if dataType === 'decimal-units'}
  <DecimalUnits {value} {unit} />
{:else if dataType === 'color-pill'}
  <ColorPill {value} />
{:else if dataType === 'relative-date'}
  <RelativeDate {value} />
{:else if dataType === 'time-format'}
  <TimeFormat {value} />
{:else if dataType === 'absolute-date'}
  <AbsoluteDate {value} />
{:else if dataType === 'truncated-text'}
  <TruncatedText {value} />
{:else if dataType === 'star-rating'}
  <StarRating {value} />
{:else}
  {value ?? ''}
{/if}

// ReactFoodFacts/src/components/table/CellRenderer.tsx
import { memo } from 'react';
import type { ColumnConfig } from '../../config/columnConfig';
import {
  TruncatedText,
  ProgressBar,
  GradeBadge,
  NovaDots,
  LargeCounter,
  DecimalUnits,
  AbsoluteDate,
  RelativeDate,
  TimeFormat,
  BooleanYesNo,
  ProductImage,
  ProductLink,
  StarRating,
  ColorPill,
} from '../display';

interface CellRendererProps {
  column: ColumnConfig;
  row: Record<string, any>;
}

export const CellRenderer = memo(({ column, row }: CellRendererProps) => {
  const value = row[column.key];

  let cell;
  if (column.type === 'product-link') {
    cell = <ProductLink code={String(row.code)} label={String(value ?? row.code)} />;
  } else if (column.type === 'simple-text') {
    cell = value ?? '';
  } else if (column.type === 'truncated-text') {
    cell = <TruncatedText value={value} />;
  } else if (column.type === 'progress-bar') {
    cell = <ProgressBar value={value ?? 0} />;
  } else if (column.type === 'grade-badge') {
    cell = <GradeBadge grade={value} />;
  } else if (column.type === 'nova-dots') {
    cell = <NovaDots rating={value} />;
  } else if (column.type === 'large-counter') {
    cell = <LargeCounter value={value} />;
  } else if (column.type === 'decimal-units' && column.unit) {
    cell = <DecimalUnits value={value} unit={column.unit} />;
  } else if (column.type === 'absolute-date') {
    cell = <AbsoluteDate value={value} />;
  } else if (column.type === 'relative-date') {
    cell = <RelativeDate value={value} />;
  } else if (column.type === 'time-format') {
    cell = <TimeFormat value={value} />;
  } else if (column.type === 'boolean-yesno') {
    cell = <BooleanYesNo value={value} />;
  } else if (column.type === 'product-image') {
    cell = <ProductImage value={value} />;
  } else if (column.type === 'star-rating') {
    cell = <StarRating value={value} />;
  } else if (column.type === 'color-pill') {
    cell = <ColorPill value={value} />;
  } else {
    cell = value ?? '';
  }

  return cell;
});

CellRenderer.displayName = 'CellRenderer';
