// SolidFoodFacts/src/components/filters/RangeSlider.tsx
import { createSignal, createEffect } from 'solid-js';
import './RangeSlider.css';

interface RangeSliderProps {
  min?: number;
  max?: number;
  resetTrigger?: number;
  onValueChange?: (value: { min: number; max: number }) => void;
}

export default function RangeSlider(props: RangeSliderProps) {
  const min = () => props.min ?? 0;
  const max = () => props.max ?? 100;

  const [minValue, setMinValue] = createSignal(min());
  const [maxValue, setMaxValue] = createSignal(max());

  // Reset when trigger changes
  createEffect(() => {
    if (props.resetTrigger) {
      setMinValue(min());
      setMaxValue(max());
    }
  });

  function handleMinChange(event: Event) {
    const target = event.target as HTMLInputElement;
    let newMin = Number(target.value);
    if (newMin > maxValue()) newMin = maxValue();
    setMinValue(newMin);
    props.onValueChange?.({ min: newMin, max: maxValue() });
  }

  function handleMaxChange(event: Event) {
    const target = event.target as HTMLInputElement;
    let newMax = Number(target.value);
    if (newMax < minValue()) newMax = minValue();
    setMaxValue(newMax);
    props.onValueChange?.({ min: minValue(), max: newMax });
  }

  return (
    <div class="range-slider">
      <input
        type="number"
        class="range-input"
        value={minValue()}
        min={min()}
        max={maxValue()}
        onInput={handleMinChange}
      />
      <span class="separator">-</span>
      <input
        type="number"
        class="range-input"
        value={maxValue()}
        min={minValue()}
        max={max()}
        onInput={handleMaxChange}
      />
    </div>
  );
}

// ReactFoodFacts/src/components/shared/filters/RangeSlider/RangeSlider.tsx
import { memo, useState, useEffect, useCallback, type ChangeEvent } from 'react';
import './RangeSlider.css';

interface RangeValue {
  min?: number;
  max?: number;
}

interface RangeSliderProps {
  min?: number;
  max?: number;
  resetTrigger?: number;
  onValueChange: (value: RangeValue) => void;
}

export const RangeSlider = memo(({
  min = 0,
  max = 100,
  resetTrigger = 0,
  onValueChange,
}: RangeSliderProps) => {
  const [minValue, setMinValue] = useState<number | undefined>(undefined);
  const [maxValue, setMaxValue] = useState<number | undefined>(undefined);

  useEffect(() => {
    setMinValue(undefined);
    setMaxValue(undefined);
  }, [resetTrigger]);

  const handleMinChange = useCallback((event: ChangeEvent<HTMLInputElement>) => {
    const value = event.target.value === '' ? undefined : Number(event.target.value);
    setMinValue(value);
  }, []);

  const handleMaxChange = useCallback((event: ChangeEvent<HTMLInputElement>) => {
    const value = event.target.value === '' ? undefined : Number(event.target.value);
    setMaxValue(value);
  }, []);

  const handleBlur = useCallback(() => {
    const result: RangeValue = {};
    if (minValue !== undefined) {
      result.min = minValue;
    }
    if (maxValue !== undefined) {
      result.max = maxValue;
    }
    onValueChange(result);
  }, [minValue, maxValue, onValueChange]);

  return (
    <div className="range-slider">
      <input
        type="number"
        className="range-input"
        min={min}
        max={max}
        value={minValue ?? ''}
        onChange={handleMinChange}
        onBlur={handleBlur}
        placeholder="Min"
      />
      <span className="range-separator">-</span>
      <input
        type="number"
        className="range-input"
        min={min}
        max={max}
        value={maxValue ?? ''}
        onChange={handleMaxChange}
        onBlur={handleBlur}
        placeholder="Max"
      />
    </div>
  );
});

RangeSlider.displayName = 'RangeSlider';
