// ReactFoodFacts/src/components/shared/Button/Button.tsx
import { memo, type ReactNode, type MouseEvent } from 'react';
import './Button.css';

interface ButtonProps {
  type?: 'button' | 'submit' | 'reset';
  disabled?: boolean;
  variant?: 'primary' | 'secondary' | 'tertiary';
  size?: 'sm' | 'md' | 'lg';
  onClick?: (event: MouseEvent<HTMLButtonElement>) => void;
  children: ReactNode;
}

export const Button = memo(({
  type = 'button',
  disabled = false,
  variant = 'secondary',
  size = 'md',
  onClick,
  children,
}: ButtonProps) => {
  const handleClick = (event: MouseEvent<HTMLButtonElement>) => {
    if (!disabled && onClick) {
      onClick(event);
    }
  };

  return (
    <button
      className={`aff-button variant-${variant} size-${size}`}
      type={type}
      disabled={disabled}
      onClick={handleClick}
    >
      {children}
    </button>
  );
});

Button.displayName = 'Button';

// SolidFoodFacts/src/components/shared/Button.tsx
import type { JSX } from 'solid-js';
import './Button.css';

interface ButtonProps {
  disabled?: boolean;
  size?: 'sm' | 'md' | 'lg';
  variant?: 'primary' | 'secondary' | 'outline';
  onClick?: () => void;
  children: JSX.Element;
}

export default function Button(props: ButtonProps) {
  const size = () => props.size || 'md';
  const variant = () => props.variant || 'secondary';

  return (
    <button
      type="button"
      class={`btn btn-${size()} btn-${variant()}`}
      disabled={props.disabled}
      onClick={props.onClick}
    >
      {props.children}
    </button>
  );
}
